// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: lrkqcgqftlffzjlpbjjy

class SupabaseConfig {
  static const String supabaseUrl = 'https://lrkqcgqftlffzjlpbjjy.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxya3FjZ3FmdGxmZnpqbHBiamp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NTIxNzcsImV4cCI6MjA4OTUyODE3N30.be7p64jzorNjQFLyHWzAYcRR4xEgqVbnzfXrAKhF18s';
}
